export const CHATS = [
	'SAMPAI DIBUAT MALU RISMON! KEMENTERIAN GELAGAPAN DICECAR PENDIDIKAN GIBRAN! --- CADAS --- RISMON VS GIBRAN',
	'SAH IJAZAH JKW TAK ADA?! UGM SAMPAI POLISI KETAKUTAN BAWA DI SIDANG! ---- CADAS --- M TAUFIQ LATAR JKW OVA EMILIA DAN KAPOLRI',
	'PRATIKNO BAKAL HADIR DI SIDANG?! GEGER PENGACARA BOCORKAN HASIL PERTEMUAN DENGAN JKW! --- CADAS --- FOTO PRATIKNO, M TAUFIQ, JKW',
	'TERUNGKAP ADA PERCAKAPAN INI SEBELUM BERTEMU JKW?! KETUA TPUA BUKA SUARA USAI DIPECAT! --- REPOT --- FOTO M TAUFIQ, muslim arbi latar jkw dan eggi sudjana',
	'JKW, UGM & KPU PANIK?! LUKAS BONJOWI BOCORKAN AGENDA SELANJUTNYA USAI MENANG SIDANG IJAZAH DI KIP!! - FOTO LUKAS TAMNEL INI https://www.youtube.com/watch?v=84V9YrkvtYM&pp=ygUNTFVLQVMgQk9OSk9XSQ%3D%3D VS JKW OVA EMILIA ORANG KIP HAKIM DAN IJAZAH',
	'RISMON BIKIN HAKIM TERCENGANG! TELANJANGI PENDIDIKAN GIBRAN DI SIDANG, KUBU KEMENTERIAN TERDIAM! --- RISMON VS GIBRAN LATAR SIDANG',
	'PRATIKNO SAMPAI PDIP AKAN DIBAWA KE SIDANG?! DICECAR HABIS, INI RENCANA SELANJUTNYA! ---- foto pratikno dan megawati-hasto',
	'SUDAH MUAK! ORANG AUSTRALIA TANTANG GIBRAN, SIAP BANTU RISMON DKK! --- foto gibran latar uts in search dan rrt',
	'XKLUSIF! "DUA BULAN LAGI TERUNGKAP IJAZAH JKW!!" 20 DOKUMEN LUKAS BONJOWI BIKIN PANIK UGM & KPU!! - BUAT GRANDE MIRIP https://www.youtube.com/watch?v=84V9YrkvtYM&pp=ygUNTFVLQVMgQk9OSk9XSQ%3D%3D,  yg tanda kutip besar, 20 dokumen sampai kpu kecil aja, Lukas, jkw, OVA emilia, hakim kip, eggi sudjana',
	'Latar warna diubah saja biar berbeda',
	'Nara hubung dibesarkan. Masih ada ruang 0. Orang tidak sulit baca'
];
export const DUMMY_TEMPLATELINE = [
	{
		id: 0,
		text: 'HELLO WORLD',
		scale: 1,
		italic: false,
		include: true
	},
	{
		id: 1,
		text: 'WE NEED MORE LOVE!',
		scale: 1,
		italic: false,
		include: true
	}
];
