// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnimationEasing = "EaseInSine" | "EaseOutSine" | "EaseInOutSine" | "EaseInQuad" | "EaseOutQuad" | "EaseInOutQuad" | "EaseInCubic" | "EaseOutCubic" | "EaseInOutCubic" | "EaseInQuart" | "EaseOutQuart" | "EaseInOutQuart" | "EaseInQuint" | "EaseOutQuint" | "EaseInOutQuint" | "EaseInExpo" | "EaseOutExpo" | "EaseInOutExpo" | "EaseInCirc" | "EaseOutCirc" | "EaseInOutCirc" | "EaseOutBack" | "EaseInOutBack" | "EaseOutElastic" | "EaseOutBounce" | "EaseInBounce";

export type AnimationPayload = { label: string, duration: number, toSize?: [number, number], toPos?: [number, number], easing: AnimationEasing, };

export type EventPayload = "tsck::event|EVENTPAYLOAD::FRONTEND" | "tsck::event|EVENTPAYLOAD::BACKEND" | "tsck::event|EVENTPAYLOAD::HOTKEE";

export type PaginationItems = { page: number, total_page: number, current_items: Array<SmartObjectItem>, };

export type SmartObjectItem = { id: number, name: string, thumb: string, };

export type SmartObjects = { smartobject_dir: string, files: Array<SmartObjectItem>, root_path: string, http_server_port: number, };

export type Texture = { id: number, category?: string, filename?: string, abs_path?: string, thumbnail?: string, favorite?: number, };

export type ToolbarPanel = { max_width?: number, height: number, padding: number, absolute: boolean, toolbar_position: ToolbarPosition, };

export type ToolbarPosition = "TopLeft" | "TopRight" | "BottomLeft" | "BottomRight";

export type UserEvent = { "type": "ReloadConfig" } | { "type": "Minimize" } | { "type": "Maximize" } | { "type": "DragWindow" } | { "type": "CloseWindow" } | { "type": "MouseDown", "value": [number, number] } | { "type": "MouseMove", "value": [number, number] } | { "type": "LaunchPlugin", "value": string } | { "type": "EvalJs", "value": string } | { "type": "LoadUrl", "value": string } | { "type": "IsOnTop" } | { "type": "NavigateWebview", "value": string } | { "type": "ZoomWebview", "value": number } | { "type": "UpdateToolbarPanel", "value": ToolbarPanel } | { "type": "SetWindowOnTop", "value": boolean } | { "type": "SetWindowDecorated", "value": boolean } | { "type": "SetWindowShadow", "value": boolean } | { "type": "SetWindowSize", "value": WindowSize } | { "type": "SetWindowPosition", "value": WindowPosition } | { "type": "TransformWindow", "value": AnimationPayload } | { "type": "SetIgnoreCursorEvent", "value": boolean } | { "type": "GoogleDownloadImage", "value": string } | { "type": "ActivateWorkSpace", "value": bigint } | { "type": "CyclePages", "value": number } | { "type": "GetActiveWindows" } | { "type": "IncomingWebsocketMessage", "value": [bigint, string] };

export type WindowInfoExt = { title: string, exe: string, class: string, size: WindowSize, position: WindowPosition, workspace: number, };

export type WindowPosition = { x: number, y: number, };

export type WindowSize = { width: number, height: number, };
