export const ComfyUiUpscaleModels = [
  "RealESRGAN_x2plus.pth",
  "001_classicalSR_DIV2K_s48w8_SwinIR-M_x2.pth",
  "003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth",
  "003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x2_GAN.pth",
  "1x-AnimeUndeint-Compact.pth",
  "1x-DeJpeg-Fatality-PlusULTRA.pth",
  "1x-ITF-SkinDiffDetail-Lite-v1.pth",
  "1x-NormalMapGenerator-CX-Lite.pth",
  "1x-ReFocus-V3.pth",
  "1x_DeBLR.pth",
  "1x_NMKD-YandereInpaint_375000_G.pth",
  "2x-Futsuu-Anime.pth",
  "2xPSNR.pth",
  "2x_Text2HD_v.1-RealPLKSR.pth",
  "4x-AnimeSharp-lite.pth",
  "4x-AnimeSharp.pth",
  "4x-ClearRealityV1.pth",
  "4x-ClearRealityV1_Soft.pth",
  "4x-UltraSharp.pth",
  "4xFaceUpLDAT.pth",
  "4xFaceUpSharpDAT.pth",
  "4xLSDIR.pth",
  "4xNMKDSuperscale_4xNMKDSuperscale.pt",
  "4xNomos2_hq_drct-l.pth",
  "4xPurePhoto-Span.pth",
  "4x_BigFace_v3.pth",
  "4x_Deviance_60000G.pth",
  "4x_NMKD-Siax_200k.pth",
  "8x_HugePaint_v1.pth",
  "8x_HugePeeps_v1.pth",
  "8x_NMKD-Faces_160000_G.pth",
  "BSRGANx2.pth",
  "DAT_2_x2.pth",
  "ESRGAN 4x.pth",
  "LDSR.ckpt",
  "RealESRGAN_x4.pth",
  "RealESRGAN_x4plus.pth",
  "Swin2SR_ClassicalSR_X2_64.pth",
  "Swin2SR_Lightweight_X2_64.pth",
  "SwinIR_4x.pth",
  "TGHQFace8x_500k.pth",
  "remacri_original.pt",
];

export const ComfyUIFaceRestoreModels = [
  "GFPGANv1.4.pth",
  "CodeFormer.pth",
  "GPEN-BFR-1024.onnx",
  "GPEN-BFR-512.onnx",
];
export const RMBGModels = ["RMBG-2.0", "INSPYRENET", "BEN", "BEN2"];
